# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Ruff

on: [push, pull_request]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11' # ou la version de python que vous ciblez

      - name: Install ruff
        run: pip install ruff

      - name: Run ruff formatter
        run: ruff format .

      - name: Run ruff linter with auto-fix
        run: ruff check . --fix

      - name: Commit changes
        # Only commit changes on push events, not on pull requests
        if: github.event_name == 'push'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: auto-format and lint with ruff"
          file_pattern: "**/*.py"